version: '3.4'

services:
    kubernetes-test-api-image:
        container_name: kubernetes-test-api2
        build: KubernetesTestApi/
        restart: always
        ports:
          - 5000:80
    prometheus:
        image: ubuntu/prometheus
        container_name: dev_prometheus
        ports:
          - "30090:9090"
        environment:
          - TZ=UTC
        volumes:
          - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana
        container_name: dev_grafana
        ports:
          - "30091:3000"
        volumes:
          - ./grafana-data/data:/var/lib/grafana

    loki:
      container_name: loki
      image: grafana/loki:master
      ports:
        - 3100:3100
      command: -config.file=/etc/loki/local-config.yaml
      healthcheck:
          test: wget -q --tries=1 -O- http://localhost:3100/ready 
          interval: 3s
          timeout: 3s
          retries: 10
          start_period: 10s
