version: '3.4'

services:
  rabbitmqdocker.webapi:
    image: ${DOCKER_REGISTRY-}rabbitmqdockerwebapi
    build:
      context: .
      dockerfile: src/RabbitMqDocker.WebApi/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgres

  rabbitmqdocker.consumer:
    image: ${DOCKER_REGISTRY-}rabbitmqdockerconsumer
    build:
      context: .
      dockerfile: src/RabbitMqDocker.Consumer/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

  postgres:
    container_name: 'postgres'
    image: postgres
    ports:
       - 5432:5432
    environment:
      # change this for a "real" app!
      POSTGRES_PASSWORD: password
    volumes:
       - ./data:/var/lib/postgresql/data
