version: '3.4'

services:
  rabbitmqdocker.webapi:
    image: ${DOCKER_REGISTRY-}rabbitmqdockerwebapi
    build:
      context: .
      dockerfile: RabbitMqDocker.WebApi/Dockerfile

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
